// ============================================================
// BERTIN'S GAMES - Catalogo Completo
// URLs corrigidas: /pt/games/{slug}/play (emulatorgamer)
//                  /pt/games/{slug} (classicgamezone)
//                  retrogames.cc/{console}-games/{slug}.html
// ============================================================

const PLATFORMS = {
  emulatorgamer: {
    name: "Emulator Gamer",
    baseUrl: "https://emulatorgamer.com",
    playUrl: (slug) => `https://emulatorgamer.com/pt/games/${slug}/play`,
    coverUrl: (slug, consoleId) => {
      const map = {nes:"nes",snes:"snes",genesis:"genesis",gba:"gba",gb:"gb",gbc:"gbc",n64:"n64",nds:"nds",psx:"ps",mastersys:"sms",arcade:"arcade"};
      const consolePath = map[consoleId] || consoleId;
      return `https://emulatorgamer.com/api/assets/covers/${consolePath}/${slug}.webp`;
    },
    color: "#ff6600"
  },
  classicgamezone: {
    name: "Classic Game Zone",
    baseUrl: "https://classicgamezone.com",
    playUrl: (slug) => `https://classicgamezone.com/pt/games/${slug}`,
    coverUrl: (slug, consoleId) => {
      const map = {nes:"nes",snes:"snes",genesis:"genesis",gba:"gba",gb:"gb",gbc:"gbc",n64:"n64",nds:"nds",psx:"ps",mastersys:"sms",arcade:"arcade"};
      const consolePath = map[consoleId] || consoleId;
      return `https://classicgamezone.com/games/covers/${consolePath}/${slug}.webp`;
    },
    color: "#00b4d8"
  },
  retrogames: {
    name: "RetroGames.cc",
    baseUrl: "https://www.retrogames.cc",
    playUrl: (slug, consoleId) => {
      const map = {nes:"nes",snes:"snes",genesis:"genesis",gba:"gba",gb:"gb",gbc:"gbc",n64:"n64",nds:"nds",psx:"psx",arcade:"arcade",mastersys:"segams"};
      const consolePath = map[consoleId] || consoleId;
      return `https://www.retrogames.cc/${consolePath}-games/${slug}.html`;
    },
    coverUrl: null,
    color: "#e63946"
  }
};

const CONSOLES = [
  { id: "nes",       name: "NES",              era: "8-bit",  year: 1983 },
  { id: "snes",      name: "Super Nintendo",   era: "16-bit", year: 1990 },
  { id: "genesis",   name: "Mega Drive",       era: "16-bit", year: 1988 },
  { id: "gba",       name: "Game Boy Advance", era: "32-bit", year: 2001 },
  { id: "gb",        name: "Game Boy",         era: "8-bit",  year: 1989 },
  { id: "gbc",       name: "Game Boy Color",   era: "8-bit",  year: 1998 },
  { id: "n64",       name: "Nintendo 64",      era: "64-bit", year: 1996 },
  { id: "nds",       name: "Nintendo DS",      era: "32-bit", year: 2004 },
  { id: "psx",       name: "PlayStation",      era: "32-bit", year: 1994 },
  { id: "arcade",    name: "Arcade",           era: "Arcade", year: 1978 },
  { id: "mastersys", name: "Master System",    era: "8-bit",  year: 1985 },
];

// Helper: get cover URL for a game from its first available source
function getCoverUrl(game) {
  if (!game.sources || game.sources.length === 0) return null;
  for (const src of game.sources) {
    const platform = PLATFORMS[src.platform];
    if (platform && typeof platform.coverUrl === "function") {
      return platform.coverUrl(src.slug, game.console);
    }
  }
  return null;
}

const GAMES_DB = [
  // =============================== NES ===============================
  { id:"smb", title:"Super Mario Bros.", console:"nes", genre:"Platformer", year:1985, players:"1-2", rating:5,
    sources:[{platform:"emulatorgamer",slug:"super-mario-bros"},{platform:"classicgamezone",slug:"super-mario-bros"}]},
  { id:"smb2", title:"Super Mario Bros. 2", console:"nes", genre:"Platformer", year:1988, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"super-mario-bros-2"},{platform:"classicgamezone",slug:"super-mario-bros-2"}]},
  { id:"smb3", title:"Super Mario Bros. 3", console:"nes", genre:"Platformer", year:1988, players:"1-2", rating:5,
    sources:[{platform:"emulatorgamer",slug:"super-mario-bros-3"},{platform:"classicgamezone",slug:"super-mario-bros-3"}]},
  { id:"zelda-nes", title:"The Legend of Zelda", console:"nes", genre:"Action RPG", year:1986, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"legend-of-zelda"},{platform:"classicgamezone",slug:"the-legend-of-zelda"}]},
  { id:"zelda2", title:"Zelda II: Adventure of Link", console:"nes", genre:"Action RPG", year:1987, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"zelda-ii-the-adventure-of-link"}]},
  { id:"megaman2", title:"Mega Man 2", console:"nes", genre:"Platformer", year:1988, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"mega-man-2"}]},
  { id:"megaman3", title:"Mega Man 3", console:"nes", genre:"Platformer", year:1990, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"mega-man-3"}]},
  { id:"megaman4", title:"Mega Man 4", console:"nes", genre:"Platformer", year:1991, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"mega-man-4"}]},
  { id:"megaman5", title:"Mega Man 5", console:"nes", genre:"Platformer", year:1992, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"mega-man-5"}]},
  { id:"megaman6", title:"Mega Man 6", console:"nes", genre:"Platformer", year:1993, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"mega-man-6"}]},
  { id:"contra-nes", title:"Contra", console:"nes", genre:"Run and Gun", year:1988, players:"1-2", rating:5,
    sources:[{platform:"emulatorgamer",slug:"contra"},{platform:"classicgamezone",slug:"contra"}]},
  { id:"contra-force", title:"Contra Force", console:"nes", genre:"Run and Gun", year:1992, players:"1-2", rating:3,
    sources:[{platform:"emulatorgamer",slug:"contra-force"}]},
  { id:"castlevania-nes", title:"Castlevania", console:"nes", genre:"Platformer", year:1986, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"castlevania"},{platform:"classicgamezone",slug:"castlevania"}]},
  { id:"castlevania2", title:"Castlevania II: Simon's Quest", console:"nes", genre:"Action RPG", year:1987, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"castlevania-ii-simons-quest"}]},
  { id:"castlevania3", title:"Castlevania III: Dracula's Curse", console:"nes", genre:"Platformer", year:1989, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"castlevania-iii-draculas-curse"}]},
  { id:"metroid-nes", title:"Metroid", console:"nes", genre:"Action", year:1986, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"metroid"},{platform:"classicgamezone",slug:"metroid"}]},
  { id:"punchout", title:"Punch-Out!!", console:"nes", genre:"Sports", year:1987, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"mike-tysons-punch-out"},{platform:"classicgamezone",slug:"mike-tysons-punch-out"}]},
  { id:"ducktales", title:"DuckTales", console:"nes", genre:"Platformer", year:1989, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"ducktales"}]},
  { id:"ducktales2", title:"DuckTales 2", console:"nes", genre:"Platformer", year:1993, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"ducktales-2"}]},
  { id:"kirby-nes", title:"Kirby's Adventure", console:"nes", genre:"Platformer", year:1993, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"kirbys-adventure"},{platform:"classicgamezone",slug:"kirbys-adventure"}]},
  { id:"tmnt2-nes", title:"TMNT II: The Arcade Game", console:"nes", genre:"Beat em up", year:1990, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"teenage-mutant-ninja-turtles-ii-the-arcade-game"}]},
  { id:"double-dragon", title:"Double Dragon", console:"nes", genre:"Beat em up", year:1988, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"double-dragon"}]},
  { id:"double-dragon2", title:"Double Dragon II", console:"nes", genre:"Beat em up", year:1989, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"double-dragon-ii-the-revenge"}]},
  { id:"double-dragon3", title:"Double Dragon III", console:"nes", genre:"Beat em up", year:1990, players:"1-2", rating:3,
    sources:[{platform:"emulatorgamer",slug:"double-dragon-iii-the-sacred-stones"}]},
  { id:"battletoads-nes", title:"Battletoads", console:"nes", genre:"Beat em up", year:1991, players:"1-2", rating:5,
    sources:[{platform:"emulatorgamer",slug:"battletoads"}]},
  { id:"battletoads-dd", title:"Battletoads & Double Dragon", console:"nes", genre:"Beat em up", year:1993, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"battletoads-double-dragon"}]},
  { id:"ninja-gaiden", title:"Ninja Gaiden", console:"nes", genre:"Action", year:1988, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"ninja-gaiden"}]},
  { id:"ninja-gaiden2", title:"Ninja Gaiden II", console:"nes", genre:"Action", year:1990, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"ninja-gaiden-ii"}]},
  { id:"ninja-gaiden3", title:"Ninja Gaiden III", console:"nes", genre:"Action", year:1991, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"ninja-gaiden-iii"}]},
  { id:"bomberman-nes", title:"Bomberman", console:"nes", genre:"Action", year:1985, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"bomberman"}]},
  { id:"bomberman2", title:"Bomberman II", console:"nes", genre:"Action", year:1991, players:"1-3", rating:4,
    sources:[{platform:"emulatorgamer",slug:"bomberman-ii"}]},
  { id:"dr-mario-nes", title:"Dr. Mario", console:"nes", genre:"Puzzle", year:1990, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"dr-mario"},{platform:"classicgamezone",slug:"dr-mario"}]},
  { id:"bubble-bobble-nes", title:"Bubble Bobble", console:"nes", genre:"Platformer", year:1988, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"bubble-bobble-nes"}]},
  { id:"burgertime", title:"BurgerTime", console:"nes", genre:"Action", year:1987, players:"1", rating:3,
    sources:[{platform:"emulatorgamer",slug:"burgertime"}]},
  { id:"chip-dale", title:"Chip 'n Dale: Rescue Rangers", console:"nes", genre:"Platformer", year:1990, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"chip-n-dale-rescue-rangers"}]},
  { id:"chip-dale2", title:"Chip 'n Dale: Rescue Rangers 2", console:"nes", genre:"Platformer", year:1993, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"chip-n-dale-rescue-rangers-2-nes"}]},
  { id:"darkwing-duck", title:"Darkwing Duck", console:"nes", genre:"Platformer", year:1992, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"darkwing-duck-nes"}]},
  { id:"dq1-nes", title:"Dragon Quest", console:"nes", genre:"RPG", year:1986, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"dragon-quest"}]},
  { id:"dq2-nes", title:"Dragon Quest II", console:"nes", genre:"RPG", year:1987, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"dragon-quest-ii"}]},
  { id:"dq3-nes", title:"Dragon Quest III", console:"nes", genre:"RPG", year:1988, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"dragon-quest-iii"}]},
  { id:"dq4-nes", title:"Dragon Quest IV", console:"nes", genre:"RPG", year:1990, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"dragon-quest-iv"}]},
  { id:"ff1-nes", title:"Final Fantasy", console:"nes", genre:"RPG", year:1987, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"final-fantasy"}]},
  { id:"ff2-nes", title:"Final Fantasy II", console:"nes", genre:"RPG", year:1988, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"final-fantasy-ii"}]},
  { id:"ff3-nes", title:"Final Fantasy III", console:"nes", genre:"RPG", year:1990, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"final-fantasy-iii"}]},
  { id:"earthbound-nes", title:"EarthBound Beginnings", console:"nes", genre:"RPG", year:1989, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"earthbound"},{platform:"classicgamezone",slug:"earthbound"}]},
  { id:"excitebike-nes", title:"Excitebike", console:"nes", genre:"Racing", year:1984, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"excitebike"},{platform:"classicgamezone",slug:"excitebike"}]},
  { id:"fire-emblem-nes", title:"Fire Emblem", console:"nes", genre:"Strategy RPG", year:1990, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"fire-emblem"}]},
  { id:"gradius-nes", title:"Gradius", console:"nes", genre:"Shooter", year:1986, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"gradius"}]},
  { id:"lolo1", title:"Adventures of Lolo", console:"nes", genre:"Puzzle", year:1989, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"adventures-of-lolo"}]},
  { id:"lolo2", title:"Adventures of Lolo 2", console:"nes", genre:"Puzzle", year:1990, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"adventures-of-lolo-2"}]},
  { id:"balloon-fight", title:"Balloon Fight", console:"nes", genre:"Action", year:1986, players:"1-2", rating:3,
    sources:[{platform:"emulatorgamer",slug:"balloon-fight"}]},
  { id:"blaster-master", title:"Blaster Master", console:"nes", genre:"Action", year:1988, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"blaster-master"}]},
  { id:"duck-hunt", title:"Duck Hunt", console:"nes", genre:"Shooter", year:1984, players:"1", rating:3,
    sources:[{platform:"emulatorgamer",slug:"duck-hunt"}]},
  { id:"faxanadu", title:"Faxanadu", console:"nes", genre:"Action RPG", year:1987, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"faxanadu"}]},
  { id:"felix-cat", title:"Felix the Cat", console:"nes", genre:"Platformer", year:1992, players:"1", rating:3,
    sources:[{platform:"emulatorgamer",slug:"felix-the-cat"}]},
  { id:"galaga-nes", title:"Galaga", console:"nes", genre:"Shooter", year:1988, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"galaga-demons-of-death"}]},
  { id:"battle-city", title:"Battle City", console:"nes", genre:"Action", year:1985, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"battle-city"}]},
  { id:"tsubasa-nes", title:"Captain Tsubasa", console:"nes", genre:"Sports", year:1988, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"captain-tsubasa"}]},
  { id:"tsubasa2-nes", title:"Captain Tsubasa Vol. II", console:"nes", genre:"Sports", year:1990, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"captain-tsubasa-vol-ii-super-striker"}]},
  { id:"donkey-kong-nes", title:"Donkey Kong", console:"nes", genre:"Platformer", year:1983, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"donkey-kong"},{platform:"classicgamezone",slug:"donkey-kong"}]},
  { id:"donkey-kong3-nes", title:"Donkey Kong 3", console:"nes", genre:"Platformer", year:1986, players:"1-2", rating:3,
    sources:[{platform:"emulatorgamer",slug:"donkey-kong-3"},{platform:"classicgamezone",slug:"donkey-kong-3"}]},
  { id:"warios-woods", title:"Wario's Woods", console:"nes", genre:"Puzzle", year:1994, players:"1-2", rating:3,
    sources:[{platform:"classicgamezone",slug:"warios-woods"}]},
  { id:"tetris-nes", title:"Tetris", console:"nes", genre:"Puzzle", year:1989, players:"1-2", rating:5,
    sources:[{platform:"classicgamezone",slug:"tetris"}]},
  // --- NES NEW ADDITIONS ---
  { id:"ice-climber", title:"Ice Climber", console:"nes", genre:"Platformer", year:1985, players:"1-2", rating:3,
    sources:[{platform:"emulatorgamer",slug:"ice-climber"}]},
  { id:"kid-icarus", title:"Kid Icarus", console:"nes", genre:"Platformer", year:1986, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"kid-icarus"}]},
  { id:"kung-fu-nes", title:"Kung Fu", console:"nes", genre:"Beat em up", year:1985, players:"1", rating:3,
    sources:[{platform:"emulatorgamer",slug:"kung-fu"}]},
  { id:"megaman1", title:"Mega Man", console:"nes", genre:"Platformer", year:1987, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"mega-man"}]},
  { id:"metal-gear-nes", title:"Metal Gear", console:"nes", genre:"Action", year:1987, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"metal-gear-nes"}]},
  { id:"jackal-nes", title:"Jackal", console:"nes", genre:"Action", year:1988, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"jackal"}]},
  { id:"gun-smoke-nes", title:"Gun.Smoke", console:"nes", genre:"Shooter", year:1988, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"gun-smoke"}]},
  { id:"mappy-nes", title:"Mappy", console:"nes", genre:"Action", year:1984, players:"1", rating:3,
    sources:[{platform:"emulatorgamer",slug:"mappy"}]},
  { id:"maniac-mansion", title:"Maniac Mansion", console:"nes", genre:"Adventure", year:1990, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"maniac-mansion"}]},
  { id:"adventure-island", title:"Hudson's Adventure Island", console:"nes", genre:"Platformer", year:1986, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"hudsons-adventure-island"}]},
  { id:"adventure-island2", title:"Hudson's Adventure Island II", console:"nes", genre:"Platformer", year:1991, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"hudsons-adventure-island-ii"}]},
  { id:"adventure-island3", title:"Hudson's Adventure Island III", console:"nes", genre:"Platformer", year:1992, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"hudsons-adventure-island-iii"}]},
  { id:"lode-runner-nes", title:"Lode Runner", console:"nes", genre:"Puzzle", year:1984, players:"1", rating:3,
    sources:[{platform:"emulatorgamer",slug:"lode-runner"}]},
  { id:"journey-silius", title:"Journey to Silius", console:"nes", genre:"Action", year:1990, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"journey-to-silius-nes"}]},
  { id:"gradius-ii-nes", title:"Gradius II", console:"nes", genre:"Shooter", year:1988, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"gradius-ii-nes"}]},

  // =============================== SNES ===============================
  { id:"smw", title:"Super Mario World", console:"snes", genre:"Platformer", year:1990, players:"1-2", rating:5,
    sources:[{platform:"emulatorgamer",slug:"super-mario-world"},{platform:"classicgamezone",slug:"super-mario-world"},{platform:"retrogames",slug:"super-mario-world-usa"}]},
  { id:"smw2", title:"Yoshi's Island", console:"snes", genre:"Platformer", year:1995, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"super-mario-world-2-yoshis-island"}]},
  { id:"zelda-lttp", title:"Zelda: A Link to the Past", console:"snes", genre:"Action RPG", year:1991, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"legend-of-zelda-a-link-to-the-past"},{platform:"retrogames",slug:"legend-of-zelda-the-a-link-to-the-past-usa"}]},
  { id:"smk", title:"Super Mario Kart", console:"snes", genre:"Racing", year:1992, players:"1-2", rating:5,
    sources:[{platform:"emulatorgamer",slug:"super-mario-kart"}]},
  { id:"sf2turbo", title:"Street Fighter II Turbo", console:"snes", genre:"Fighting", year:1993, players:"1-2", rating:5,
    sources:[{platform:"emulatorgamer",slug:"street-fighter-ii-turbo"},{platform:"retrogames",slug:"street-fighter-ii-turbo-hyper-fighting-usa"}]},
  { id:"dkc", title:"Donkey Kong Country", console:"snes", genre:"Platformer", year:1994, players:"1-2", rating:5,
    sources:[{platform:"emulatorgamer",slug:"donkey-kong-country"},{platform:"retrogames",slug:"donkey-kong-country-usa"}]},
  { id:"dkc2", title:"Donkey Kong Country 2", console:"snes", genre:"Platformer", year:1995, players:"1-2", rating:5,
    sources:[{platform:"emulatorgamer",slug:"donkey-kong-country-2-diddys-kong-quest"}]},
  { id:"dkc3", title:"Donkey Kong Country 3", console:"snes", genre:"Platformer", year:1996, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"donkey-kong-country-3-dixie-kongs-double-trouble"}]},
  { id:"chrono-trigger", title:"Chrono Trigger", console:"snes", genre:"RPG", year:1995, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"chrono-trigger"},{platform:"retrogames",slug:"chrono-trigger-usa"}]},
  { id:"ff4-snes", title:"Final Fantasy IV", console:"snes", genre:"RPG", year:1991, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"final-fantasy-iv"}]},
  { id:"ff5-snes", title:"Final Fantasy V", console:"snes", genre:"RPG", year:1992, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"final-fantasy-v"}]},
  { id:"ff6", title:"Final Fantasy VI", console:"snes", genre:"RPG", year:1994, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"final-fantasy-vi"},{platform:"retrogames",slug:"final-fantasy-vi-usa"}]},
  { id:"supermetroid", title:"Super Metroid", console:"snes", genre:"Action", year:1994, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"super-metroid"},{platform:"retrogames",slug:"super-metroid-usa"}]},
  { id:"mmx", title:"Mega Man X", console:"snes", genre:"Platformer", year:1993, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"mega-man-x"},{platform:"retrogames",slug:"mega-man-x-usa"}]},
  { id:"mmx2", title:"Mega Man X2", console:"snes", genre:"Platformer", year:1994, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"mega-man-x2"}]},
  { id:"mmx3", title:"Mega Man X3", console:"snes", genre:"Platformer", year:1995, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"mega-man-x3"}]},
  { id:"earthbound-snes", title:"EarthBound", console:"snes", genre:"RPG", year:1994, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"earthbound-2"}]},
  { id:"smrpg", title:"Super Mario RPG", console:"snes", genre:"RPG", year:1996, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"super-mario-rpg"}]},
  { id:"secret-mana", title:"Secret of Mana", console:"snes", genre:"Action RPG", year:1993, players:"1-3", rating:5,
    sources:[{platform:"emulatorgamer",slug:"secret-of-mana"}]},
  { id:"contra3", title:"Contra III: The Alien Wars", console:"snes", genre:"Run and Gun", year:1992, players:"1-2", rating:5,
    sources:[{platform:"emulatorgamer",slug:"contra-iii"}]},
  { id:"actraiser", title:"ActRaiser", console:"snes", genre:"Action", year:1990, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"actraiser"}]},
  { id:"aladdin-snes", title:"Aladdin", console:"snes", genre:"Platformer", year:1993, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"aladdin"}]},
  { id:"fzero", title:"F-Zero", console:"snes", genre:"Racing", year:1990, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"f-zero"}]},
  { id:"earthworm-jim-snes", title:"Earthworm Jim", console:"snes", genre:"Platformer", year:1994, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"earthworm-jim"}]},
  { id:"earthworm-jim2", title:"Earthworm Jim 2", console:"snes", genre:"Platformer", year:1995, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"earthworm-jim-2"}]},
  { id:"illusion-gaia", title:"Illusion of Gaia", console:"snes", genre:"Action RPG", year:1993, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"illusion-of-gaia"}]},
  { id:"harvest-moon-snes", title:"Harvest Moon", console:"snes", genre:"Simulation", year:1996, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"harvest-moon-snes"}]},
  { id:"goof-troop", title:"Goof Troop", console:"snes", genre:"Action", year:1993, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"goof-troop"}]},
  { id:"gradius3", title:"Gradius III", console:"snes", genre:"Shooter", year:1990, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"gradius-iii-snes"}]},
  { id:"breath-fire", title:"Breath of Fire", console:"snes", genre:"RPG", year:1993, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"breath-of-fire"}]},
  { id:"breath-fire2", title:"Breath of Fire II", console:"snes", genre:"RPG", year:1994, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"breath-of-fire-ii"}]},
  { id:"castlevania-dracula-x", title:"Castlevania: Dracula X", console:"snes", genre:"Platformer", year:1995, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"castlevania-dracula-x-snes"}]},
  { id:"clock-tower", title:"Clock Tower", console:"snes", genre:"Horror", year:1995, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"clock-tower"}]},
  { id:"battletoads-bm", title:"Battletoads in Battlemaniacs", console:"snes", genre:"Beat em up", year:1993, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"battletoads-in-battlemaniacs"}]},
  { id:"btdd-snes", title:"Battletoads & Double Dragon", console:"snes", genre:"Beat em up", year:1993, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"battletoads-double-dragon-snes"}]},
  { id:"cybernator", title:"Cybernator", console:"snes", genre:"Action", year:1992, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"cybernator"}]},
  { id:"evo", title:"E.V.O.: Search for Eden", console:"snes", genre:"Action RPG", year:1992, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"evo-search-for-eden"}]},
  { id:"front-mission", title:"Front Mission", console:"snes", genre:"Strategy RPG", year:1995, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"front-mission"}]},
  { id:"fire-emblem-snes", title:"Fire Emblem: Genealogy of the Holy War", console:"snes", genre:"Strategy RPG", year:1996, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"fire-emblem-genealogy-of-the-holy-war"}]},
  { id:"ganpuru", title:"Gunman's Proof", console:"snes", genre:"Action", year:1997, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"ganpuru-gunmans-proof"}]},
  { id:"hagane", title:"Hagane: The Final Conflict", console:"snes", genre:"Action", year:1994, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"hagane-the-final-conflict"}]},
  { id:"dbz-hd", title:"Dragon Ball Z: Hyper Dimension", console:"snes", genre:"Fighting", year:1996, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"dragon-ball-z-chomutujeon"}]},
  { id:"dbz-sb3", title:"Dragon Ball Z: Super Butouden 3", console:"snes", genre:"Fighting", year:1994, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"dragon-ball-z-super-butouden-3"}]},
  { id:"final-fight2", title:"Final Fight 2", console:"snes", genre:"Beat em up", year:1993, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"final-fight-2"}]},
  { id:"final-fight3", title:"Final Fight 3", console:"snes", genre:"Beat em up", year:1995, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"final-fight-3"}]},
  { id:"blackthorne-snes", title:"Blackthorne", console:"snes", genre:"Action", year:1994, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"blackthorne-snes"}]},
  { id:"axelay", title:"Axelay", console:"snes", genre:"Shooter", year:1992, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"axelay"}]},
  { id:"dqv-snes", title:"Dragon Quest V", console:"snes", genre:"RPG", year:1992, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"dragon-quest-v-tenkuu-no-hanayome"}]},
  { id:"dqvi-snes", title:"Dragon Quest VI", console:"snes", genre:"RPG", year:1995, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"dragon-quest-vi"}]},
  { id:"tsubasa3-snes", title:"Captain Tsubasa III", console:"snes", genre:"Sports", year:1992, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"captain-tsubasa-iii"}]},
  { id:"tsubasa4-snes", title:"Captain Tsubasa IV", console:"snes", genre:"Sports", year:1993, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"captain-tsubasa-iv-pro-no-rival-tachi"}]},
  { id:"tsubasa5-snes", title:"Captain Tsubasa V", console:"snes", genre:"Sports", year:1994, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"captain-tsubasa-v-hasha-no-shougou-campione"}]},
  // --- SNES NEW ADDITIONS ---
  { id:"killer-instinct-snes", title:"Killer Instinct", console:"snes", genre:"Fighting", year:1994, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"killer-instinct"}]},
  { id:"king-of-dragons", title:"King of Dragons", console:"snes", genre:"Beat em up", year:1994, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"king-of-dragons"}]},
  { id:"kirby-super-star", title:"Kirby Super Star", console:"snes", genre:"Platformer", year:1996, players:"1-2", rating:5,
    sources:[{platform:"emulatorgamer",slug:"kirby-super-star"}]},
  { id:"kirby-dl3-snes", title:"Kirby's Dream Land 3", console:"snes", genre:"Platformer", year:1997, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"kirbys-dream-land-3"}]},
  { id:"knights-round", title:"Knights of the Round", console:"snes", genre:"Beat em up", year:1991, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"knights-of-the-round-snes"}]},
  { id:"lufia1", title:"Lufia and the Fortress of Doom", console:"snes", genre:"RPG", year:1993, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"lufia-and-the-fortress-of-doom"}]},
  { id:"lufia2", title:"Lufia II: Rise of the Sinistrals", console:"snes", genre:"RPG", year:1995, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"lufia-ii-rise-of-the-sinistrals"}]},
  { id:"megaman7", title:"Mega Man 7", console:"snes", genre:"Platformer", year:1995, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"mega-man-7"}]},
  { id:"secret-evermore", title:"Secret of Evermore", console:"snes", genre:"Action RPG", year:1995, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"secret-of-evermore"}]},
  { id:"prince-persia-snes", title:"Prince of Persia", console:"snes", genre:"Platformer", year:1992, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"prince-of-persia-snes"}]},
  { id:"rtype3-snes", title:"R-Type III", console:"snes", genre:"Shooter", year:1993, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"r-type-iii-snes"}]},
  { id:"romancing-saga1", title:"Romancing SaGa", console:"snes", genre:"RPG", year:1992, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"romancing-saga"}]},
  { id:"romancing-saga2", title:"Romancing SaGa 2", console:"snes", genre:"RPG", year:1993, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"romancing-saga-2"}]},
  { id:"romancing-saga3", title:"Romancing SaGa 3", console:"snes", genre:"RPG", year:1995, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"romancing-saga-3"}]},
  { id:"simcity-snes", title:"SimCity", console:"snes", genre:"Simulation", year:1991, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"simcity"}]},
  { id:"ogre-battle-snes", title:"Ogre Battle: The March of the Black Queen", console:"snes", genre:"Strategy RPG", year:1993, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"ogre-battle-the-march-of-the-black-queen"}]},
  { id:"smt2-snes", title:"Shin Megami Tensei II", console:"snes", genre:"RPG", year:1994, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"shin-megami-tensei-ii"}]},
  { id:"iss-snes", title:"International Superstar Soccer", console:"snes", genre:"Sports", year:1994, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"international-superstar-soccer"}]},
  { id:"nba-jam-te-snes", title:"NBA Jam Tournament Edition", console:"snes", genre:"Sports", year:1994, players:"1-4", rating:4,
    sources:[{platform:"emulatorgamer",slug:"nba-jam-tournament-edition-snes"}]},
  { id:"mmpr-fighting", title:"Mighty Morphin Power Rangers: The Fighting Edition", console:"snes", genre:"Fighting", year:1995, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"mighty-morphin-power-rangers-the-fighting-edition"}]},
  { id:"joe-mac-snes", title:"Joe & Mac", console:"snes", genre:"Platformer", year:1991, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"joe-and-mac"}]},
  { id:"sailor-moon-snes", title:"Bishoujo Senshi Sailor Moon", console:"snes", genre:"Beat em up", year:1993, players:"1-2", rating:3,
    sources:[{platform:"emulatorgamer",slug:"bishoujo-senshi-sailor-moon"}]},
  { id:"popn-twinbee", title:"Pop'n TwinBee", console:"snes", genre:"Shooter", year:1993, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"popn-twinbee"}]},
  { id:"inspector-gadget-snes", title:"Inspector Gadget", console:"snes", genre:"Platformer", year:1993, players:"1", rating:3,
    sources:[{platform:"emulatorgamer",slug:"inspector-gadget"}]},
  { id:"rockman-forte", title:"Mega Man & Bass", console:"snes", genre:"Platformer", year:1998, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"rockman-forte"}]},

  // =============================== MEGA DRIVE / GENESIS ===============================
  { id:"sonic1", title:"Sonic the Hedgehog", console:"genesis", genre:"Platformer", year:1991, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"sonic-the-hedgehog-jue"},{platform:"classicgamezone",slug:"sonic-the-hedgehog"}]},
  { id:"sonic2", title:"Sonic the Hedgehog 2", console:"genesis", genre:"Platformer", year:1992, players:"1-2", rating:5,
    sources:[{platform:"emulatorgamer",slug:"sonic-the-hedgehog-2"},{platform:"classicgamezone",slug:"sonic-the-hedgehog-2"}]},
  { id:"sonic3", title:"Sonic the Hedgehog 3", console:"genesis", genre:"Platformer", year:1994, players:"1-2", rating:5,
    sources:[{platform:"emulatorgamer",slug:"sonic-the-hedgehog-3"}]},
  { id:"sonic-knuckles", title:"Sonic & Knuckles", console:"genesis", genre:"Platformer", year:1994, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"sonic-knuckles"}]},
  { id:"sonic3d", title:"Sonic 3D Blast", console:"genesis", genre:"Platformer", year:1996, players:"1", rating:3,
    sources:[{platform:"emulatorgamer",slug:"sonic-3d-blast-genesis"}]},
  { id:"streets-rage", title:"Streets of Rage", console:"genesis", genre:"Beat em up", year:1991, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"streets-of-rage"}]},
  { id:"streets-rage2", title:"Streets of Rage 2", console:"genesis", genre:"Beat em up", year:1992, players:"1-2", rating:5,
    sources:[{platform:"emulatorgamer",slug:"streets-of-rage-2"}]},
  { id:"streets-rage3", title:"Streets of Rage 3", console:"genesis", genre:"Beat em up", year:1994, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"streets-of-rage-3"}]},
  { id:"golden-axe", title:"Golden Axe", console:"genesis", genre:"Beat em up", year:1989, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"golden-axe"}]},
  { id:"golden-axe2", title:"Golden Axe II", console:"genesis", genre:"Beat em up", year:1991, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"golden-axe-ii"}]},
  { id:"golden-axe3", title:"Golden Axe III", console:"genesis", genre:"Beat em up", year:1993, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"golden-axe-iii"}]},
  { id:"mortal-kombat-gen", title:"Mortal Kombat", console:"genesis", genre:"Fighting", year:1993, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"mortal-kombat"}]},
  { id:"shinobi3", title:"Shinobi III", console:"genesis", genre:"Action", year:1993, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"shinobi-3-return-of-the-ninja-master"}]},
  { id:"gunstar-heroes", title:"Gunstar Heroes", console:"genesis", genre:"Run and Gun", year:1993, players:"1-2", rating:5,
    sources:[{platform:"emulatorgamer",slug:"gunstar-heroes"}]},
  { id:"altered-beast", title:"Altered Beast", console:"genesis", genre:"Beat em up", year:1988, players:"1-2", rating:3,
    sources:[{platform:"emulatorgamer",slug:"altered-beast"}]},
  { id:"phantasy-star2", title:"Phantasy Star II", console:"genesis", genre:"RPG", year:1989, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"phantasy-star-ii"}]},
  { id:"phantasy-star4", title:"Phantasy Star IV", console:"genesis", genre:"RPG", year:1993, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"phantasy-star-iv"}]},
  { id:"comix-zone", title:"Comix Zone", console:"genesis", genre:"Beat em up", year:1995, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"comix-zone"}]},
  { id:"contra-hard", title:"Contra: Hard Corps", console:"genesis", genre:"Run and Gun", year:1994, players:"1-2", rating:5,
    sources:[{platform:"emulatorgamer",slug:"contra-hard-corps"}]},
  { id:"castlevania-blood", title:"Castlevania: Bloodlines", console:"genesis", genre:"Platformer", year:1994, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"castlevania-bloodlines"}]},
  { id:"shining-force", title:"Shining Force", console:"genesis", genre:"Strategy RPG", year:1992, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"shining-force"}]},
  { id:"shining-force2", title:"Shining Force II", console:"genesis", genre:"Strategy RPG", year:1993, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"shining-force-ii"}]},
  { id:"rocket-knight", title:"Rocket Knight Adventures", console:"genesis", genre:"Platformer", year:1993, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"rocket-knight-adventures"}]},
  { id:"ristar", title:"Ristar", console:"genesis", genre:"Platformer", year:1995, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"ristar-the-shooting-star"}]},
  { id:"road-rash2", title:"Road Rash II", console:"genesis", genre:"Racing", year:1992, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"road-rash-ii"}]},
  { id:"pulseman", title:"Pulseman", console:"genesis", genre:"Platformer", year:1994, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"pulseman"}]},
  { id:"aladdin-gen", title:"Disney's Aladdin", console:"genesis", genre:"Platformer", year:1993, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"disney-aladdin"}]},
  { id:"castle-illusion", title:"Castle of Illusion", console:"genesis", genre:"Platformer", year:1990, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"castle-of-illusion-starring-mickey-mouse"}]},
  { id:"quackshot", title:"QuackShot", console:"genesis", genre:"Platformer", year:1991, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"quackshot-starring-donald-duck"}]},
  { id:"nba-jam-gen", title:"NBA Jam Tournament Edition", console:"genesis", genre:"Sports", year:1994, players:"1-4", rating:4,
    sources:[{platform:"emulatorgamer",slug:"nba-jam-tournament-edition-genesis"}]},
  { id:"moonwalker", title:"Michael Jackson's Moonwalker", console:"genesis", genre:"Action", year:1990, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"michael-jacksons-moonwalker"}]},
  { id:"landstalker", title:"Landstalker", console:"genesis", genre:"Action RPG", year:1992, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"landstalker-treasures-of-king-nole"}]},
  { id:"splatterhouse2", title:"Splatterhouse 2", console:"genesis", genre:"Action", year:1992, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"splatterhouse-2"}]},
  { id:"panorama-cotton", title:"Panorama Cotton", console:"genesis", genre:"Shooter", year:1994, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"panorama-cotton"}]},
  { id:"alien-soldier", title:"Alien Soldier", console:"genesis", genre:"Action", year:1995, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"alien-soldier"}]},
  { id:"musha", title:"MUSHA", console:"genesis", genre:"Shooter", year:1990, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"musha"}]},
  { id:"strider-gen", title:"Strider", console:"genesis", genre:"Action", year:1990, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"strider-genesis"}]},
  { id:"spider-man-gen", title:"Spider-Man", console:"genesis", genre:"Action", year:1991, players:"1", rating:3,
    sources:[{platform:"emulatorgamer",slug:"spider-man-genesis"}]},
  { id:"power-rangers-gen", title:"Mighty Morphin Power Rangers", console:"genesis", genre:"Fighting", year:1994, players:"1-2", rating:3,
    sources:[{platform:"emulatorgamer",slug:"mighty-morphin-power-rangers-genesis"}]},

  // =============================== GBA ===============================
  { id:"pokemon-emerald", title:"Pokemon Emerald", console:"gba", genre:"RPG", year:2004, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"pokemon-emerald"}]},
  { id:"pokemon-firered", title:"Pokemon FireRed", console:"gba", genre:"RPG", year:2004, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"pokemon-fire-red"}]},
  { id:"zelda-minish", title:"Zelda: The Minish Cap", console:"gba", genre:"Action RPG", year:2004, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"legend-of-zelda-the-minish-cap"}]},
  { id:"advance-wars", title:"Advance Wars", console:"gba", genre:"Strategy", year:2001, players:"1-4", rating:5,
    sources:[{platform:"emulatorgamer",slug:"advance-wars"}]},
  { id:"advance-wars2", title:"Advance Wars 2", console:"gba", genre:"Strategy", year:2003, players:"1-4", rating:5,
    sources:[{platform:"emulatorgamer",slug:"advance-wars-2-black-hole-rising"}]},
  { id:"metroid-fusion", title:"Metroid Fusion", console:"gba", genre:"Action", year:2002, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"metroid-fusion"}]},
  { id:"castlevania-aria", title:"Castlevania: Aria of Sorrow", console:"gba", genre:"Action RPG", year:2003, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"castlevania-aria-of-sorrow"}]},
  { id:"castlevania-cotm", title:"Castlevania: Circle of the Moon", console:"gba", genre:"Action RPG", year:2001, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"castlevania-circle-of-the-moon"}]},
  { id:"castlevania-hod", title:"Castlevania: Harmony of Dissonance", console:"gba", genre:"Action RPG", year:2002, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"castlevania-harmony-of-dissonance"}]},
  { id:"fire-emblem-gba", title:"Fire Emblem", console:"gba", genre:"Strategy RPG", year:2003, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"fire-emblem"}]},
  { id:"golden-sun", title:"Golden Sun", console:"gba", genre:"RPG", year:2001, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"golden-sun"}]},
  { id:"mario-luigi-ss", title:"Mario & Luigi: Superstar Saga", console:"gba", genre:"RPG", year:2003, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"mario-and-luigi-superstar-saga"}]},
  { id:"astro-boy", title:"Astro Boy: Omega Factor", console:"gba", genre:"Action", year:2003, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"astro-boy-omega-factor"}]},
  { id:"contra-advance", title:"Contra Advance", console:"gba", genre:"Run and Gun", year:2002, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"contra-advance"}]},
  { id:"crash-huge", title:"Crash Bandicoot: The Huge Adventure", console:"gba", genre:"Platformer", year:2002, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"crash-bandicoot-the-huge-adventure"}]},
  { id:"crash-ntranced", title:"Crash Bandicoot 2: N-Tranced", console:"gba", genre:"Platformer", year:2003, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"crash-bandicoot-2-n-tranced"}]},
  { id:"doom-gba", title:"DOOM", console:"gba", genre:"FPS", year:2001, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"doom"}]},
  { id:"mmbn3", title:"Mega Man Battle Network 3", console:"gba", genre:"Action RPG", year:2002, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"mega-man-battle-network-3-blue"}]},
  // --- GBA NEW ADDITIONS ---
  { id:"fe-blazing", title:"Fire Emblem: The Blazing Blade", console:"gba", genre:"Strategy RPG", year:2003, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"fire-emblem-the-blazing-blade"}]},
  { id:"fe-sacred-stones", title:"Fire Emblem: The Sacred Stones", console:"gba", genre:"Strategy RPG", year:2004, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"fire-emblem-sacred-stones"}]},
  { id:"fe-binding-blade", title:"Fire Emblem: The Binding Blade", console:"gba", genre:"Strategy RPG", year:2002, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"fire-emblem-the-binding-blade"}]},
  { id:"golden-sun-tla", title:"Golden Sun: The Lost Age", console:"gba", genre:"RPG", year:2002, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"golden-sun-the-lost-age"}]},
  { id:"fft-advance", title:"Final Fantasy Tactics Advance", console:"gba", genre:"Strategy RPG", year:2003, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"final-fantasy-tactics-advance"}]},
  { id:"ff6-advance", title:"Final Fantasy VI Advance", console:"gba", genre:"RPG", year:2006, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"final-fantasy-vi-advance"}]},
  { id:"ff4-advance", title:"Final Fantasy IV Advance", console:"gba", genre:"RPG", year:2005, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"final-fantasy-iv-advance"}]},
  { id:"ff12-advance", title:"Final Fantasy I & II Advance", console:"gba", genre:"RPG", year:2004, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"final-fantasy-1-2-advance"}]},
  { id:"kh-com", title:"Kingdom Hearts: Chain of Memories", console:"gba", genre:"Action RPG", year:2004, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"kingdom-hearts-chain-of-memories"}]},
  { id:"kirby-nightmare", title:"Kirby: Nightmare in Dream Land", console:"gba", genre:"Platformer", year:2002, players:"1-4", rating:4,
    sources:[{platform:"emulatorgamer",slug:"kirby-nightmare-in-dream-land"}]},
  { id:"kirby-mirror", title:"Kirby & The Amazing Mirror", console:"gba", genre:"Platformer", year:2004, players:"1-4", rating:4,
    sources:[{platform:"emulatorgamer",slug:"kirby-amazing-mirror"}]},
  { id:"mk-super-circuit", title:"Mario Kart: Super Circuit", console:"gba", genre:"Racing", year:2001, players:"1-4", rating:4,
    sources:[{platform:"emulatorgamer",slug:"mario-kart-super-circuit-gba"}]},
  { id:"mmzero1", title:"Mega Man Zero", console:"gba", genre:"Platformer", year:2002, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"mega-man-zero"}]},
  { id:"mmzero2", title:"Mega Man Zero 2", console:"gba", genre:"Platformer", year:2003, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"mega-man-zero-2"}]},
  { id:"gunstar-sh", title:"Gunstar Super Heroes", console:"gba", genre:"Action", year:2005, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"gunstar-super-heroes"}]},
  { id:"hm-fomt", title:"Harvest Moon: Friends of Mineral Town", console:"gba", genre:"Simulation", year:2003, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"harvest-moon-friends-of-mineral-town"}]},
  { id:"drill-dozer", title:"Drill Dozer", console:"gba", genre:"Action", year:2005, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"drill-dozer"}]},
  { id:"db-adv-adventure", title:"Dragon Ball: Advanced Adventure", console:"gba", genre:"Action", year:2004, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"dragon-ball-advanced-adventure"}]},
  { id:"dbz-log2", title:"Dragon Ball Z: Legacy of Goku II", console:"gba", genre:"Action RPG", year:2003, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"dragon-ball-z-legacy-of-goku-2"}]},
  { id:"klonoa-eod", title:"Klonoa: Empire of Dreams", console:"gba", genre:"Platformer", year:2001, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"klonoa-empire-of-dreams-gba"}]},
  { id:"gta-advance", title:"Grand Theft Auto Advance", console:"gba", genre:"Action", year:2004, players:"1", rating:3,
    sources:[{platform:"emulatorgamer",slug:"grand-theft-auto-advance"}]},
  { id:"mario-vs-dk", title:"Mario vs. Donkey Kong", console:"gba", genre:"Puzzle", year:2004, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"mario-vs-donkey-kong-gba"}]},

  // =============================== GAME BOY ===============================
  { id:"pokemon-yellow", title:"Pokemon Yellow", console:"gb", genre:"RPG", year:1998, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"pokemon-yellow"}]},
  { id:"zelda-la", title:"Zelda: Link's Awakening", console:"gb", genre:"Action RPG", year:1993, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"legend-of-zelda-links-awakening"}]},
  { id:"tetris-gb", title:"Tetris", console:"gb", genre:"Puzzle", year:1989, players:"1-2", rating:5,
    sources:[{platform:"emulatorgamer",slug:"tetris"}]},
  { id:"kirby-dl", title:"Kirby's Dream Land", console:"gb", genre:"Platformer", year:1992, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"kirbys-dream-land"}]},
  { id:"kirby-dl2", title:"Kirby's Dream Land 2", console:"gb", genre:"Platformer", year:1995, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"kirby-dream-land-2"}]},
  { id:"sml2", title:"Super Mario Land 2", console:"gb", genre:"Platformer", year:1992, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"super-mario-land-2-6-golden-coins"}]},
  { id:"castlevania-adventure", title:"Castlevania: The Adventure", console:"gb", genre:"Platformer", year:1989, players:"1", rating:3,
    sources:[{platform:"emulatorgamer",slug:"castlevania-the-adventure"}]},
  { id:"castlevania-br", title:"Castlevania II: Belmont's Revenge", console:"gb", genre:"Platformer", year:1991, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"castlevania-ii-belmonts-revenge-gb"}]},
  { id:"ff-adventure", title:"Final Fantasy Adventure", console:"gb", genre:"Action RPG", year:1991, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"final-fantasy-adventure-gb"}]},
  { id:"harvest-moon-gb", title:"Harvest Moon GB", console:"gb", genre:"Simulation", year:1997, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"harvest-moon-gb"}]},
  { id:"dw12-gb", title:"Dragon Warrior I & II", console:"gb", genre:"RPG", year:1999, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"dragon-warrior-i-ii"}]},
  { id:"dw3-gb", title:"Dragon Warrior III", console:"gb", genre:"RPG", year:2001, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"dragon-warrior-iii"}]},
  { id:"bomberman-quest", title:"Bomberman Quest", console:"gb", genre:"Action", year:1998, players:"1", rating:3,
    sources:[{platform:"emulatorgamer",slug:"bomberman-quest"}]},

  // =============================== GBC ===============================
  { id:"pokemon-crystal", title:"Pokemon Crystal", console:"gbc", genre:"RPG", year:2000, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"pokemon-crystal"}]},
  { id:"zelda-oracle-ages", title:"Zelda: Oracle of Ages", console:"gbc", genre:"Action RPG", year:2001, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"legend-of-zelda-oracle-of-ages"}]},
  { id:"dw3-gbc", title:"Dragon Warrior III (GBC)", console:"gbc", genre:"RPG", year:2001, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"dragon-warrior-iii"}]},
  { id:"dqm-gbc", title:"Dragon Quest Monsters", console:"gbc", genre:"RPG", year:1998, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"dragon-quest-monsters-terry"}]},

  // =============================== N64 ===============================
  { id:"sm64", title:"Super Mario 64", console:"n64", genre:"Platformer", year:1996, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"super-mario-64"}]},
  { id:"zelda-oot", title:"Zelda: Ocarina of Time", console:"n64", genre:"Action RPG", year:1998, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"legend-of-zelda-ocarina-of-time"}]},
  { id:"zelda-mm", title:"Zelda: Majora's Mask", console:"n64", genre:"Action RPG", year:2000, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"legend-of-zelda-majoras-mask"}]},
  { id:"mariokart64", title:"Mario Kart 64", console:"n64", genre:"Racing", year:1996, players:"1-4", rating:5,
    sources:[{platform:"emulatorgamer",slug:"mario-kart-64"}]},
  { id:"goldeneye", title:"GoldenEye 007", console:"n64", genre:"FPS", year:1997, players:"1-4", rating:5,
    sources:[{platform:"emulatorgamer",slug:"goldeneye-007-64"}]},
  { id:"smash64", title:"Super Smash Bros.", console:"n64", genre:"Fighting", year:1999, players:"1-4", rating:5,
    sources:[{platform:"emulatorgamer",slug:"super-smash-bros"}]},
  { id:"banjo-kazooie", title:"Banjo-Kazooie", console:"n64", genre:"Platformer", year:1998, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"banjo-kazooie"}]},
  { id:"banjo-tooie", title:"Banjo-Tooie", console:"n64", genre:"Platformer", year:2000, players:"1-4", rating:5,
    sources:[{platform:"emulatorgamer",slug:"banjo-tooie-n64"}]},
  { id:"paper-mario", title:"Paper Mario", console:"n64", genre:"RPG", year:2000, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"paper-mario"}]},
  { id:"starfox64", title:"Star Fox 64", console:"n64", genre:"Shooter", year:1997, players:"1-4", rating:5,
    sources:[{platform:"emulatorgamer",slug:"star-fox-64"}]},
  { id:"dk64", title:"Donkey Kong 64", console:"n64", genre:"Platformer", year:1999, players:"1-4", rating:4,
    sources:[{platform:"emulatorgamer",slug:"donkey-kong-64"}]},
  { id:"fzero-x", title:"F-Zero X", console:"n64", genre:"Racing", year:1998, players:"1-4", rating:5,
    sources:[{platform:"emulatorgamer",slug:"f-zero-x"}]},
  { id:"conkers", title:"Conker's Bad Fur Day", console:"n64", genre:"Platformer", year:2001, players:"1-4", rating:5,
    sources:[{platform:"emulatorgamer",slug:"conkers-bad-fur-day"}]},
  { id:"diddy-racing", title:"Diddy Kong Racing", console:"n64", genre:"Racing", year:1997, players:"1-4", rating:5,
    sources:[{platform:"emulatorgamer",slug:"diddy-kong-racing"}]},
  { id:"kirby64", title:"Kirby 64: The Crystal Shards", console:"n64", genre:"Platformer", year:2000, players:"1-4", rating:4,
    sources:[{platform:"emulatorgamer",slug:"kirby-64-crystal-shards"}]},
  { id:"harvest-moon64", title:"Harvest Moon 64", console:"n64", genre:"Simulation", year:1999, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"harvest-moon-64"}]},
  { id:"jet-force", title:"Jet Force Gemini", console:"n64", genre:"Action", year:1999, players:"1-4", rating:4,
    sources:[{platform:"emulatorgamer",slug:"jet-force-gemini"}]},
  { id:"killer-instinct", title:"Killer Instinct Gold", console:"n64", genre:"Fighting", year:1996, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"killer-instinct-gold"}]},
  { id:"doom64", title:"Doom 64", console:"n64", genre:"FPS", year:1997, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"doom-64"}]},
  { id:"bomberman64", title:"Bomberman 64", console:"n64", genre:"Action", year:1997, players:"1-4", rating:4,
    sources:[{platform:"emulatorgamer",slug:"bomberman-64"}]},
  { id:"castlevania-n64", title:"Castlevania", console:"n64", genre:"Action", year:1999, players:"1", rating:3,
    sources:[{platform:"emulatorgamer",slug:"castlevania-n64"}]},
  { id:"castlevania-lod", title:"Castlevania: Legacy of Darkness", console:"n64", genre:"Action", year:1999, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"castlevania-legacy-of-darkness-n64"}]},
  { id:"excitebike64", title:"Excitebike 64", console:"n64", genre:"Racing", year:2000, players:"1-4", rating:4,
    sources:[{platform:"emulatorgamer",slug:"excitebike-64"}]},
  { id:"1080snow", title:"1080 Snowboarding", console:"n64", genre:"Sports", year:1998, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"1080-snowboarding"}]},
  { id:"dr-mario64", title:"Dr. Mario 64", console:"n64", genre:"Puzzle", year:2001, players:"1-4", rating:4,
    sources:[{platform:"emulatorgamer",slug:"dr-mario-64"}]},
  { id:"hydro-thunder", title:"Hydro Thunder", console:"n64", genre:"Racing", year:2000, players:"1-4", rating:4,
    sources:[{platform:"emulatorgamer",slug:"hydro-thunder"}]},
  // --- N64 NEW ADDITIONS ---
  { id:"mario-party1", title:"Mario Party", console:"n64", genre:"Party", year:1998, players:"1-4", rating:4,
    sources:[{platform:"emulatorgamer",slug:"mario-party"}]},
  { id:"mario-party2", title:"Mario Party 2", console:"n64", genre:"Party", year:1999, players:"1-4", rating:5,
    sources:[{platform:"emulatorgamer",slug:"mario-party-2"}]},
  { id:"mario-party3", title:"Mario Party 3", console:"n64", genre:"Party", year:2000, players:"1-4", rating:5,
    sources:[{platform:"emulatorgamer",slug:"mario-party-3"}]},
  { id:"mario-tennis64", title:"Mario Tennis", console:"n64", genre:"Sports", year:2000, players:"1-4", rating:4,
    sources:[{platform:"emulatorgamer",slug:"mario-tennis-64"}]},
  { id:"mario-golf64", title:"Mario Golf", console:"n64", genre:"Sports", year:1999, players:"1-4", rating:4,
    sources:[{platform:"emulatorgamer",slug:"mario-golf-n64"}]},
  { id:"perfect-dark", title:"Perfect Dark", console:"n64", genre:"FPS", year:2000, players:"1-4", rating:5,
    sources:[{platform:"emulatorgamer",slug:"perfect-dark"}]},
  { id:"pokemon-snap", title:"Pokemon Snap", console:"n64", genre:"Action", year:1999, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"pokemon-snap"}]},
  { id:"pokemon-stadium", title:"Pokemon Stadium", console:"n64", genre:"Fighting", year:1999, players:"1-4", rating:4,
    sources:[{platform:"emulatorgamer",slug:"pokemon-stadium"}]},
  { id:"pokemon-stadium2", title:"Pokemon Stadium 2", console:"n64", genre:"Fighting", year:2000, players:"1-4", rating:4,
    sources:[{platform:"emulatorgamer",slug:"pokemon-stadium-2"}]},
  { id:"mk4-n64", title:"Mortal Kombat 4", console:"n64", genre:"Fighting", year:1998, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"mortal-kombat-4"}]},
  { id:"mk-trilogy", title:"Mortal Kombat Trilogy", console:"n64", genre:"Fighting", year:1996, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"mortal-kombat-trilogy"}]},
  { id:"rayman2-n64", title:"Rayman 2: The Great Escape", console:"n64", genre:"Platformer", year:1999, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"rayman-2-n64"}]},
  { id:"re2-n64", title:"Resident Evil 2", console:"n64", genre:"Horror", year:1999, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"resident-evil-2"}]},
  { id:"ogre-battle64", title:"Ogre Battle 64: Person of Lordly Caliber", console:"n64", genre:"Strategy RPG", year:2000, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"ogre-battle-64-person-of-lordly-caliber"}]},
  { id:"quake-n64", title:"Quake", console:"n64", genre:"FPS", year:1998, players:"1-4", rating:4,
    sources:[{platform:"emulatorgamer",slug:"quake-n64"}]},
  { id:"snowboard-kids", title:"Snowboard Kids", console:"n64", genre:"Sports", year:1997, players:"1-4", rating:4,
    sources:[{platform:"emulatorgamer",slug:"snowboard-kids-n64"}]},
  { id:"ridge-racer64", title:"Ridge Racer 64", console:"n64", genre:"Racing", year:2000, players:"1-4", rating:4,
    sources:[{platform:"emulatorgamer",slug:"ridge-racer-64"}]},
  { id:"road-rash64", title:"Road Rash 64", console:"n64", genre:"Racing", year:1999, players:"1-4", rating:3,
    sources:[{platform:"emulatorgamer",slug:"road-rash-64"}]},
  { id:"mischief-makers", title:"Mischief Makers", console:"n64", genre:"Platformer", year:1997, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"mischief-makers"}]},
  { id:"megaman64", title:"Mega Man 64", console:"n64", genre:"Action RPG", year:2001, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"mega-man-64"}]},

  // =============================== NDS ===============================
  { id:"pokemon-platinum", title:"Pokemon Platinum", console:"nds", genre:"RPG", year:2008, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"pokemon-platinum"}]},
  { id:"pokemon-hg", title:"Pokemon HeartGold", console:"nds", genre:"RPG", year:2009, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"pokemon-heartgold"}]},
  { id:"mario-kart-ds", title:"Mario Kart DS", console:"nds", genre:"Racing", year:2005, players:"1-8", rating:5,
    sources:[{platform:"emulatorgamer",slug:"mario-kart-ds"}]},
  { id:"new-smb", title:"New Super Mario Bros.", console:"nds", genre:"Platformer", year:2006, players:"1-2", rating:5,
    sources:[{platform:"emulatorgamer",slug:"new-super-mario-bros"}]},
  { id:"zelda-ph", title:"Zelda: Phantom Hourglass", console:"nds", genre:"Action RPG", year:2007, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"legend-of-zelda-phantom-hourglass"}]},
  { id:"castlevania-dos", title:"Castlevania: Dawn of Sorrow", console:"nds", genre:"Action RPG", year:2005, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"castlevania-dawn-of-sorrow"}]},
  { id:"castlevania-por", title:"Castlevania: Portrait of Ruin", console:"nds", genre:"Action RPG", year:2006, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"castlevania-portrait-of-ruin"}]},
  { id:"chrono-trigger-ds", title:"Chrono Trigger (DS)", console:"nds", genre:"RPG", year:2008, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"chrono-trigger-nds"}]},
  { id:"advance-wars-ds", title:"Advance Wars: Dual Strike", console:"nds", genre:"Strategy", year:2005, players:"1-8", rating:5,
    sources:[{platform:"emulatorgamer",slug:"advance-wars-dual-strike"}]},
  { id:"kirby-ssu", title:"Kirby Super Star Ultra", console:"nds", genre:"Platformer", year:2008, players:"1-4", rating:5,
    sources:[{platform:"emulatorgamer",slug:"kirby-super-star-ultra"}]},
  { id:"gta-cw", title:"GTA: Chinatown Wars", console:"nds", genre:"Action", year:2009, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"grand-theft-auto-chinatown-wars"}]},
  { id:"animal-crossing-ww", title:"Animal Crossing: Wild World", console:"nds", genre:"Simulation", year:2005, players:"1-4", rating:4,
    sources:[{platform:"emulatorgamer",slug:"animal-crossing-wild-world"}]},
  { id:"dqv-ds", title:"Dragon Quest V (DS)", console:"nds", genre:"RPG", year:2008, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"dragon-quest-v-hand-of-the-heavenly-bride"}]},
  { id:"dqvi-ds", title:"Dragon Quest VI (DS)", console:"nds", genre:"RPG", year:2010, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"dragon-quest-vi-realms-of-revelation"}]},
  // --- NDS NEW ADDITIONS ---
  { id:"digimon-world-ds", title:"Digimon World DS", console:"nds", genre:"RPG", year:2006, players:"1", rating:3,
    sources:[{platform:"emulatorgamer",slug:"digimon-world-ds"}]},
  { id:"dbz-sw2-ds", title:"Dragon Ball Z: Supersonic Warriors 2", console:"nds", genre:"Fighting", year:2005, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"dragon-ball-z-supersonic-warriors-2"}]},

  // =============================== PLAYSTATION ===============================
  { id:"ff7", title:"Final Fantasy VII", console:"psx", genre:"RPG", year:1997, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"final-fantasy-vii"}]},
  { id:"ff8", title:"Final Fantasy VIII", console:"psx", genre:"RPG", year:1999, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"final-fantasy-viii"}]},
  { id:"ff9", title:"Final Fantasy IX", console:"psx", genre:"RPG", year:2000, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"final-fantasy-ix"}]},
  { id:"fft", title:"Final Fantasy Tactics", console:"psx", genre:"Strategy RPG", year:1997, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"final-fantasy-tactics"}]},
  { id:"mgs", title:"Metal Gear Solid", console:"psx", genre:"Stealth", year:1998, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"metal-gear-solid"}]},
  { id:"mgs-vr", title:"Metal Gear Solid: VR Missions", console:"psx", genre:"Stealth", year:1999, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"metal-gear-solid-vr-missions"}]},
  { id:"crash1", title:"Crash Bandicoot", console:"psx", genre:"Platformer", year:1996, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"crash-bandicoot"}]},
  { id:"crash2", title:"Crash Bandicoot 2", console:"psx", genre:"Platformer", year:1997, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"crash-bandicoot-2-cortex-strikes-back"}]},
  { id:"crash3", title:"Crash Bandicoot 3: Warped", console:"psx", genre:"Platformer", year:1998, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"crash-bandicoot-3-warped"}]},
  { id:"ctr", title:"Crash Team Racing", console:"psx", genre:"Racing", year:1999, players:"1-4", rating:5,
    sources:[{platform:"emulatorgamer",slug:"crash-team-racing"}]},
  { id:"re2", title:"Resident Evil 2", console:"psx", genre:"Horror", year:1998, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"resident-evil-2-ps"}]},
  { id:"re3", title:"Resident Evil 3: Nemesis", console:"psx", genre:"Horror", year:1999, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"resident-evil-3-nemesis"}]},
  { id:"re-dc", title:"Resident Evil: Director's Cut", console:"psx", genre:"Horror", year:1997, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"resident-evil-directors-cut-dual-shock"}]},
  { id:"silent-hill", title:"Silent Hill", console:"psx", genre:"Horror", year:1999, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"silent-hill"}]},
  { id:"spyro1", title:"Spyro the Dragon", console:"psx", genre:"Platformer", year:1998, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"spyro-the-dragon"}]},
  { id:"spyro2", title:"Spyro 2: Ripto's Rage", console:"psx", genre:"Platformer", year:1999, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"spyro-2-riptos-rage-ps"}]},
  { id:"spyro3", title:"Spyro 3: Year of the Dragon", console:"psx", genre:"Platformer", year:2000, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"spyro-3-year-of-the-dragon"}]},
  { id:"tekken1", title:"Tekken", console:"psx", genre:"Fighting", year:1995, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"tekken"}]},
  { id:"tekken2", title:"Tekken 2", console:"psx", genre:"Fighting", year:1996, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"tekken-2"}]},
  { id:"tekken3", title:"Tekken 3", console:"psx", genre:"Fighting", year:1997, players:"1-2", rating:5,
    sources:[{platform:"emulatorgamer",slug:"tekken-3"}]},
  { id:"castlevania-sotn", title:"Castlevania: Symphony of the Night", console:"psx", genre:"Action RPG", year:1997, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"castlevania-symphony-of-the-night"}]},
  { id:"chrono-cross", title:"Chrono Cross", console:"psx", genre:"RPG", year:1999, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"chrono-cross"}]},
  { id:"gran-turismo", title:"Gran Turismo", console:"psx", genre:"Racing", year:1997, players:"1-2", rating:5,
    sources:[{platform:"emulatorgamer",slug:"gran-turismo"}]},
  { id:"gran-turismo2", title:"Gran Turismo 2", console:"psx", genre:"Racing", year:1999, players:"1-2", rating:5,
    sources:[{platform:"emulatorgamer",slug:"gran-turismo-2-plus"}]},
  { id:"dino-crisis", title:"Dino Crisis", console:"psx", genre:"Horror", year:1999, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"dino-crisis"}]},
  { id:"dino-crisis2", title:"Dino Crisis II", console:"psx", genre:"Action", year:2000, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"dino-crisis-ii"}]},
  { id:"parasite-eve", title:"Parasite Eve", console:"psx", genre:"RPG", year:1998, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"parasite-eve"}]},
  { id:"parasite-eve2", title:"Parasite Eve II", console:"psx", genre:"Action", year:1999, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"parasite-eve-2"}]},
  { id:"xenogears", title:"Xenogears", console:"psx", genre:"RPG", year:1998, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"xenogears"}]},
  { id:"vagrant-story", title:"Vagrant Story", console:"psx", genre:"Action RPG", year:2000, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"vagrant-story"}]},
  { id:"valkyrie-profile", title:"Valkyrie Profile", console:"psx", genre:"RPG", year:1999, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"valkyrie-profile"}]},
  { id:"suikoden", title:"Suikoden", console:"psx", genre:"RPG", year:1995, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"suikoden"}]},
  { id:"suikoden2", title:"Suikoden II", console:"psx", genre:"RPG", year:1998, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"suikoden-ii"}]},
  { id:"wild-arms", title:"Wild Arms", console:"psx", genre:"RPG", year:1996, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"wild-arms"}]},
  { id:"wild-arms2", title:"Wild Arms 2", console:"psx", genre:"RPG", year:1999, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"wild-arms-2"}]},
  { id:"persona-ps", title:"Persona: Revelations", console:"psx", genre:"RPG", year:1996, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"persona-revelations"}]},
  { id:"persona2-ep", title:"Persona 2: Eternal Punishment", console:"psx", genre:"RPG", year:2000, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"persona-2-eternal-punishment"}]},
  { id:"tomb-raider", title:"Tomb Raider", console:"psx", genre:"Action", year:1996, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"tomb-raider"}]},
  { id:"tomb-raider2", title:"Tomb Raider II", console:"psx", genre:"Action", year:1997, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"tomb-raider-2"}]},
  { id:"tony-hawk", title:"Tony Hawk's Pro Skater", console:"psx", genre:"Sports", year:1999, players:"1-2", rating:5,
    sources:[{platform:"emulatorgamer",slug:"tony-hawk-pro-skater-ps"}]},
  { id:"tony-hawk2", title:"Tony Hawk's Pro Skater 2", console:"psx", genre:"Sports", year:2000, players:"1-2", rating:5,
    sources:[{platform:"emulatorgamer",slug:"tony-hawk-pro-skater-2-ps"}]},
  { id:"tony-hawk3", title:"Tony Hawk's Pro Skater 3", console:"psx", genre:"Sports", year:2001, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"tony-hawk-pro-skater-3-ps"}]},
  { id:"twisted-metal", title:"Twisted Metal", console:"psx", genre:"Vehicular Combat", year:1995, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"twisted-metal"}]},
  { id:"twisted-metal2", title:"Twisted Metal 2", console:"psx", genre:"Vehicular Combat", year:1996, players:"1-2", rating:5,
    sources:[{platform:"emulatorgamer",slug:"twisted-metal-2"}]},
  { id:"syphon-filter", title:"Syphon Filter", console:"psx", genre:"Action", year:1999, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"syphon-filter"}]},
  { id:"syphon-filter2", title:"Syphon Filter 2", console:"psx", genre:"Action", year:2000, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"syphon-filter-2"}]},
  { id:"driver", title:"Driver", console:"psx", genre:"Racing", year:1999, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"driver-wheelman"}]},
  { id:"driver2", title:"Driver 2", console:"psx", genre:"Racing", year:2000, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"driver-2-back-on-the-streets"}]},
  { id:"medievil", title:"MediEvil", console:"psx", genre:"Action", year:1998, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"medievil"}]},
  { id:"medievil2", title:"MediEvil 2", console:"psx", genre:"Action", year:2000, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"medievil-2"}]},
  { id:"klonoa", title:"Klonoa: Door to Phantomile", console:"psx", genre:"Platformer", year:1997, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"klonoa-door-to-phantomile"}]},
  { id:"legacy-kain", title:"Legacy of Kain: Soul Reaver", console:"psx", genre:"Action", year:1999, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"legacy-of-kain-soul-reaver"}]},
  { id:"legend-mana", title:"Legend of Mana", console:"psx", genre:"Action RPG", year:1999, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"legend-of-mana"}]},
  { id:"mmx4", title:"Mega Man X4", console:"psx", genre:"Platformer", year:1997, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"mega-man-x4"}]},
  { id:"mmx5", title:"Mega Man X5", console:"psx", genre:"Platformer", year:2000, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"mega-man-x5"}]},
  { id:"mm-legends", title:"Mega Man Legends", console:"psx", genre:"Action RPG", year:1997, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"mega-man-legends"}]},
  { id:"mm8", title:"Mega Man 8", console:"psx", genre:"Platformer", year:1996, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"mega-man-8"}]},
  { id:"harvest-moon-btn", title:"Harvest Moon: Back to Nature", console:"psx", genre:"Simulation", year:1999, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"harvest-moon-back-to-nature"}]},
  { id:"digimon-world", title:"Digimon World", console:"psx", genre:"RPG", year:1999, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"digimon-world"}]},
  { id:"digimon-world2", title:"Digimon World 2", console:"psx", genre:"RPG", year:2000, players:"1", rating:3,
    sources:[{platform:"emulatorgamer",slug:"digimon-world-2"}]},
  { id:"digimon-world3", title:"Digimon World 3", console:"psx", genre:"RPG", year:2002, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"digimon-world-3"}]},
  { id:"breath-fire3", title:"Breath of Fire III", console:"psx", genre:"RPG", year:1997, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"breath-of-fire-iii"}]},
  { id:"breath-fire4", title:"Breath of Fire IV", console:"psx", genre:"RPG", year:2000, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"breath-of-fire-iv"}]},
  { id:"brave-fencer", title:"Brave Fencer Musashi", console:"psx", genre:"Action RPG", year:1998, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"brave-fencer-musashi"}]},
  { id:"parappa", title:"PaRappa the Rapper", console:"psx", genre:"Rhythm", year:1996, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"parappa-the-rapper"}]},
  { id:"pepsiman", title:"Pepsiman", console:"psx", genre:"Action", year:1999, players:"1", rating:3,
    sources:[{platform:"emulatorgamer",slug:"pepsiman"}]},
  { id:"yugioh-fm", title:"Yu-Gi-Oh! Forbidden Memories", console:"psx", genre:"Card Game", year:1999, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"yugioh-forbidden-memories"}]},
  { id:"dbz-ub22", title:"Dragon Ball Z: Ultimate Battle 22", console:"psx", genre:"Fighting", year:1995, players:"1-2", rating:3,
    sources:[{platform:"emulatorgamer",slug:"dragon-ball-z-ultimate-battle-22"}]},
  { id:"dbgt-fb", title:"Dragon Ball GT: Final Bout", console:"psx", genre:"Fighting", year:1997, players:"1-2", rating:3,
    sources:[{platform:"emulatorgamer",slug:"dragon-ball-gt-final-bout"}]},
  { id:"gta1", title:"Grand Theft Auto", console:"psx", genre:"Action", year:1997, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"grand-theft-auto"}]},
  { id:"gta2", title:"Grand Theft Auto 2", console:"psx", genre:"Action", year:1999, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"grand-theft-auto-2"}]},
  { id:"diablo-ps", title:"Diablo", console:"psx", genre:"Action RPG", year:1998, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"diablo"}]},
  { id:"grandia-ps", title:"Grandia", console:"psx", genre:"RPG", year:1999, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"grandia"}]},
  { id:"tales-destiny", title:"Tales of Destiny", console:"psx", genre:"RPG", year:1997, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"tales-of-destiny"}]},
  { id:"tales-destiny2", title:"Tales of Destiny II", console:"psx", genre:"RPG", year:2000, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"tales-of-destiny-ii"}]},
  { id:"tactics-ogre", title:"Tactics Ogre", console:"psx", genre:"Strategy RPG", year:1998, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"tactics-ogre-ps"}]},
  { id:"road-rash-ps", title:"Road Rash", console:"psx", genre:"Racing", year:1995, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"road-rash"}]},
  { id:"spider-man-ps", title:"Spider-Man", console:"psx", genre:"Action", year:2000, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"spider-man-ps"}]},
  { id:"ridgeracer4", title:"Ridge Racer Type 4", console:"psx", genre:"Racing", year:1998, players:"1-2", rating:5,
    sources:[{platform:"emulatorgamer",slug:"ridge-racer-type-4"}]},
  { id:"rival-schools", title:"Rival Schools", console:"psx", genre:"Fighting", year:1998, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"rival-schools-united-by-fate"}]},
  { id:"darkstalkers3", title:"Darkstalkers 3", console:"psx", genre:"Fighting", year:1998, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"darkstalkers-3"}]},
  { id:"wwf-smackdown", title:"WWF SmackDown!", console:"psx", genre:"Fighting", year:2000, players:"1-4", rating:4,
    sources:[{platform:"emulatorgamer",slug:"wwf-smackdown"}]},
  { id:"ape-escape", title:"Ape Escape", console:"psx", genre:"Platformer", year:1999, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"ape-escape"}]},
  { id:"alundra", title:"Alundra", console:"psx", genre:"Action RPG", year:1997, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"alundra"}]},
  { id:"r-type-delta", title:"R-Type Delta", console:"psx", genre:"Shooter", year:1998, players:"1", rating:5,
    sources:[{platform:"emulatorgamer",slug:"r-type-delta"}]},
  { id:"vandal-hearts", title:"Vandal Hearts", console:"psx", genre:"Strategy RPG", year:1996, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"vandal-hearts"}]},
  { id:"threads-fate", title:"Threads of Fate", console:"psx", genre:"Action RPG", year:1999, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"threads-of-fate"}]},
  { id:"disney-hercules", title:"Disney's Hercules", console:"psx", genre:"Platformer", year:1997, players:"1", rating:3,
    sources:[{platform:"emulatorgamer",slug:"disney-hercules-ps"}]},
  { id:"disney-tarzan", title:"Disney's Tarzan", console:"psx", genre:"Platformer", year:1999, players:"1", rating:3,
    sources:[{platform:"emulatorgamer",slug:"disney-tarzan"}]},
  { id:"toy-story2", title:"Toy Story 2", console:"psx", genre:"Platformer", year:1999, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"toy-story-2-buzz-lightyear-to-the-rescue"}]},
  { id:"tenchu", title:"Tenchu: Stealth Assassins", console:"psx", genre:"Stealth", year:1998, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"tenchu-stealth-assassins"}]},
  { id:"tenchu2", title:"Tenchu 2", console:"psx", genre:"Stealth", year:2000, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"tenchu-2-birth-of-the-stealth-assassins"}]},
  { id:"medal-honor", title:"Medal of Honor", console:"psx", genre:"FPS", year:1999, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"medal-of-honor"}]},
  { id:"medal-honor-u", title:"Medal of Honor: Underground", console:"psx", genre:"FPS", year:2000, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"medal-of-honor-underground"}]},
  { id:"theme-hospital", title:"Theme Hospital", console:"psx", genre:"Simulation", year:1997, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"theme-hospital-ps"}]},
  { id:"castlevania-chron", title:"Castlevania Chronicles", console:"psx", genre:"Platformer", year:2001, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"castlevania-chronicles"}]},
  { id:"pac-man-world", title:"Pac-Man World", console:"psx", genre:"Platformer", year:1999, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"pac-man-world"}]},
  { id:"strider-ps", title:"Strider", console:"psx", genre:"Action", year:1999, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"strider-ps"}]},
  { id:"strider2", title:"Strider 2", console:"psx", genre:"Action", year:1999, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"strider-2"}]},
  { id:"jojos-ps", title:"JoJo's Bizarre Adventure", console:"psx", genre:"Fighting", year:1999, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"jojos-bizarre-adventure-ps"}]},
  { id:"guilty-gear-ps", title:"Guilty Gear", console:"psx", genre:"Fighting", year:1998, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"guilty-gear-ps"}]},
  { id:"wipeout", title:"Wipeout 2097", console:"psx", genre:"Racing", year:1996, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"wipeout-2097"}]},
  { id:"saga-frontier", title:"SaGa Frontier", console:"psx", genre:"RPG", year:1997, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"saga-frontier"}]},
  { id:"dead-or-alive-ps", title:"Dead or Alive", console:"psx", genre:"Fighting", year:1998, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"dead-or-alive"}]},
  // --- PSX NEW ADDITIONS ---
  { id:"clock-tower-ff", title:"Clock Tower: The First Fear", console:"psx", genre:"Horror", year:1997, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"clock-tower-the-first-fear"}]},
  { id:"bomberman-pe", title:"Bomberman Party Edition", console:"psx", genre:"Action", year:1998, players:"1-4", rating:4,
    sources:[{platform:"emulatorgamer",slug:"bomberman-party-edition"}]},
  { id:"ace-combat2", title:"Ace Combat 2", console:"psx", genre:"Flight", year:1997, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"ace-combat-2"}]},
  { id:"ace-combat3", title:"Ace Combat 3: Electrosphere", console:"psx", genre:"Flight", year:1999, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"ace-combat-3"}]},
  { id:"alundra2", title:"Alundra 2", console:"psx", genre:"Action RPG", year:2000, players:"1", rating:3,
    sources:[{platform:"emulatorgamer",slug:"alundra-2"}]},
  { id:"jumping-flash", title:"Jumping Flash!", console:"psx", genre:"Platformer", year:1995, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"jumping-flash"}]},
  { id:"front-mission2", title:"Front Mission 2", console:"psx", genre:"Strategy RPG", year:1997, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"front-mission-2"}]},
  { id:"time-crisis-ps", title:"Time Crisis", console:"psx", genre:"Shooter", year:1997, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"time-crisis"}]},
  { id:"bushido-blade", title:"Bushido Blade", console:"psx", genre:"Fighting", year:1997, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"bushido-blade-ps"}]},
  { id:"initial-d-ps", title:"Initial D", console:"psx", genre:"Racing", year:1998, players:"1", rating:3,
    sources:[{platform:"emulatorgamer",slug:"initial-d-ps"}]},

  // =============================== ARCADE ===============================
  { id:"pacman", title:"Pac-Man", console:"arcade", genre:"Maze", year:1980, players:"1-2", rating:5,
    sources:[{platform:"emulatorgamer",slug:"pac-man"}]},
  { id:"galaga", title:"Galaga", console:"arcade", genre:"Shooter", year:1981, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"galaga"}]},
  { id:"sf2-arcade", title:"Street Fighter II", console:"arcade", genre:"Fighting", year:1991, players:"1-2", rating:5,
    sources:[{platform:"emulatorgamer",slug:"street-fighter-ii-the-world-warrior"}]},
  { id:"metal-slug", title:"Metal Slug", console:"arcade", genre:"Run and Gun", year:1996, players:"1-2", rating:5,
    sources:[{platform:"emulatorgamer",slug:"metal-slug"}]},
  { id:"kof98", title:"King of Fighters '98", console:"arcade", genre:"Fighting", year:1998, players:"1-2", rating:5,
    sources:[{platform:"emulatorgamer",slug:"king-of-fighters-98"}]},
  { id:"dkong-arc", title:"Donkey Kong", console:"arcade", genre:"Platformer", year:1981, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"donkey-kong"}]},
  { id:"space-invaders", title:"Space Invaders", console:"arcade", genre:"Shooter", year:1978, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"space-invaders"}]},
  { id:"1942-arc", title:"1942", console:"arcade", genre:"Shooter", year:1984, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"1942"}]},
  { id:"1943-arc", title:"1943: Battle of Midway", console:"arcade", genre:"Shooter", year:1987, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"1943-battle-of-midway"}]},
  { id:"avp-arc", title:"Alien vs. Predator", console:"arcade", genre:"Beat em up", year:1994, players:"1-3", rating:5,
    sources:[{platform:"emulatorgamer",slug:"alien-vs-predator"}]},
  { id:"aero-fighters", title:"Aero Fighters", console:"arcade", genre:"Shooter", year:1992, players:"1-2", rating:4,
    sources:[{platform:"emulatorgamer",slug:"aero-fighters"}]},

  // =============================== MASTER SYSTEM ===============================
  { id:"alex-kidd", title:"Alex Kidd in Miracle World", console:"mastersys", genre:"Platformer", year:1986, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"alex-kidd-in-miracle-world-sms"}]},
  { id:"sonic-ms", title:"Sonic the Hedgehog (MS)", console:"mastersys", genre:"Platformer", year:1991, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"sonic-the-hedgehog-sega-master-system"}]},
  { id:"castle-illusion-ms", title:"Castle of Illusion (MS)", console:"mastersys", genre:"Platformer", year:1990, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"castle-of-illusion-sms"}]},
  { id:"california-games-ms", title:"California Games", console:"mastersys", genre:"Sports", year:1989, players:"1-8", rating:3,
    sources:[{platform:"emulatorgamer",slug:"california-games-sms"}]},
  { id:"after-burner-ms", title:"After Burner", console:"mastersys", genre:"Shooter", year:1987, players:"1", rating:3,
    sources:[{platform:"emulatorgamer",slug:"after-burner-sms"}]},
  { id:"aleste-ms", title:"Aleste", console:"mastersys", genre:"Shooter", year:1988, players:"1", rating:4,
    sources:[{platform:"emulatorgamer",slug:"aleste-sms"}]},
  { id:"black-belt-ms", title:"Black Belt", console:"mastersys", genre:"Beat em up", year:1986, players:"1", rating:3,
    sources:[{platform:"emulatorgamer",slug:"black-belt-sms"}]},
  { id:"choplifter-ms", title:"Choplifter", console:"mastersys", genre:"Action", year:1986, players:"1", rating:3,
    sources:[{platform:"emulatorgamer",slug:"choplifter-sms"}]},
  { id:"aerial-assault-ms", title:"Aerial Assault", console:"mastersys", genre:"Shooter", year:1990, players:"1", rating:3,
    sources:[{platform:"emulatorgamer",slug:"aerial-assault"}]},
  { id:"batman-returns-ms", title:"Batman Returns", console:"mastersys", genre:"Action", year:1993, players:"1", rating:3,
    sources:[{platform:"emulatorgamer",slug:"batman-returns-sms"}]},
];

const GENRES = [...new Set(GAMES_DB.map(g => g.genre))].sort();
